name: Compatibility Matrix

on:
  workflow_dispatch:

jobs:
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        keycloak_version: [ 26.2.4, latest, nightly ]
        extension_version: [ 26.0.0 ]
    name: KC ${{ matrix.keycloak_version }}, Extension ${{ matrix.extension_version }}
    steps:
      - uses: actions/checkout@v4
        with:
            ref: v${{ matrix.extension_version }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Clean and compile
        run: mvn -B -U clean test-compile --file pom.xml
      - name: Download extension
        run: curl -L -o target/keycloak-kommons.jar https://github.com/sventorben/keycloak-kommons/releases/download/v${{ matrix.extension_version }}/keycloak-kommons.jar
      - name: Compatibility tests
        run: mvn -B -U failsafe:integration-test failsafe:verify --file pom.xml -Dkeycloak.version=${{ matrix.keycloak_version }} -DuseJar=true
